import { readFileSync, writeFileSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';

const root = join(dirname(fileURLToPath(import.meta.url)), '..');
const pkg = JSON.parse(readFileSync(join(root, 'package.json'), 'utf8'));

if (!/^[0-9A-Za-z.+-]{1,64}$/.test(pkg.version)) {
  throw new Error(`version ${pkg.version} is not accepted by the bridge contract`);
}

const out = `// Generated by scripts/gen-version.mjs. Do not edit by hand.
// Reported by \`mentiora/initialize\`; must match /^[0-9A-Za-z.+-]{1,64}$/.
export const SDK_NAME = '${pkg.name}';
export const SDK_VERSION = '${pkg.version}';
`;

const target = join(root, 'src', 'version.ts');
const current = readFileSync(target, 'utf8');
if (current !== out) {
  writeFileSync(target, out);
  console.log(`src/version.ts updated to ${pkg.version}`);
} else {
  console.log(`src/version.ts already at ${pkg.version}`);
}
