// Generated by scripts/gen-version.mjs. Do not edit by hand.
// Reported by `mentiora/initialize`; must match /^[0-9A-Za-z.+-]{1,64}$/.
export const SDK_NAME = '@mentiora-ai/react-native-sdk';
export const SDK_VERSION = '0.1.0';
